### PR TITLE
Change LoadConf to not escape %#! in passwords as it causes auth issues

### PR DESCRIPTION
**Pull request by AniAggarwal**
Made a new branch and updated it to work with #22. Will close #27 as I made that PR incorrectly/poorly. 

This PR updates the README and get rid of password substitutions.

### CODE REVIEW

**Comment by KenN7** [comment]
Hi, could you squash you commits ? The current commit history still shows you adding and then removing the rsync flag feature, which is not something that should show up in the commit history of the repository

**Comment by AniAggarwal** [comment]
Makes sense.

Any suggestions on how to do that without squashing your PR merge commits as well?

**Comment by KenN7** [comment]
I think that at this point, instead of merging the new commits, you should have rebased on them.
When you rebase, the new commits will be added before your commits, then you could just add you first commit  (Change LoadConf  ... ) and last commit (Readme) on top, by cherry picking them

**Comment by AniAggarwal** [comment]
Alright. I'll close this one too and create a new PR with everything done (hopefully) correctly.
Sorry about making a mess of this.

**Pull request closed without merging**
